export const filmsData = [
  {
    id: 1,
    image: "/images/spiderman.png",
    title: "Spider-Man: Across the Spider-Verse",
    year: "2023",
    nation: "USA",
    description:
      "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.",
    directors: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
    writers:
      "David Callaham, Phil Lord, Christopher Miller, Stan Lee, Steve Ditko",
    actor: "Shameik Moore, Hailee Steinfeld, Brian Tyree Henry",
    genres: "Action, Adventure, Animation, Comedy, Family, Sci-Fi",
    duration: "117 min",
    language: "English",
    releaseDate: "2 June 2023",
    disambiguation: "PG-13",
    rating: 8.4,
    trailer: "https://www.youtube.com/embed/cqGjhVJWtEg",
  },
  {
    id: 2,
    image: "/images/batman.png",
    title: "The Dark Knight",
    year: "2008",
    nation: "USA",
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    directors: "Christopher Nolan",
    writers: "Jonathan Nolan, Christopher Nolan, David S. Goyer, Bob Kane",
    actor: "Christian Bale, Heath Ledger, Aaron Eckhart",
    genres: "Action, Crime, Drama, Thriller",
    duration: "152 min",
    language: "English, Mandarin",
    releaseDate: "18 July 2008",
    disambiguation: "PG-13",
    rating: 9,
    trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
  },
  {
    id: 3,
    image: "/images/avatar2.png",
    title: "Avatar: The Way of Water",
    year: "2022",
    nation: "USA",
    description:
      "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Navi race to protect their home.",
    directors: "James Cameron",
    writers: "James Cameron",
    actor: "Zoe Saldana, Kate Winslet, Vin Diesel",
    genres: "Action, Adventure, Fantasy, Sci-Fi",
    duration: "156 min",
    language: "English",
    releaseDate: "16 December 2022",
    disambiguation: "PG-13",
    rating: 7.8,
    trailer: "https://www.youtube.com/embed/d9MyW72ELq0",
  },
  {
    id: 4,
    image: "/images/thewolf.png",
    title: "The Wolf of Wall Street",
    year: "2013",
    nation: "USA",
    description:
      "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
    directors: "Martin Scorsese",
    writers: "Terence Winter, Jordan Belfort",
    actor: "Leonardo DiCaprio, Jonah Hill, Margot Robbie",
    genres: "Biography, Crime, Drama",
    duration: "180 min",
    language: "English, French",
    releaseDate: "25 December 2013",
    disambiguation: "R",
    rating: 8.2,
    trailer: "https://www.youtube.com/embed/iszwuX1AK6A",
  },
  {
    id: 5,
    image: "/images/openheimer.png",
    title: "Oppenheimer",
    year: "2023",
    nation: "USA",
    description:
      "Based on the 2005 biography American Prometheus by Kai Bird and Martin J. Sherwin, the film chronicles the career of Oppenheimer with the story predominantly focusing on his studies, his direction of the Manhattan Project during World War II, and his eventual fall from grace due to his 1954 security hearing.",
    directors: "Christopher Nolan",
    writers: "Christopher Nolan",
    actor: "Cillian Murphy, Emily Blunt, Matt Damon",
    genres: "Biography, Drama, History",
    duration: "120 min",
    language: "English",
    releaseDate: "21 July 2023",
    disambiguation: "PG-13",
    rating: 7.8,
    trailer: "https://www.youtube.com/embed/uYPbbksJxIg",
  },
  {
    id: 6,
    image: "/images/yourname.png",
    title: "Your Name.",
    year: "2016",
    nation: "Japan",
    description:
      "Two teenagers share a profound, magical connection upon discovering they are swapping bodies. Things manage to become even more complicated when the boy and girl decide to meet in person.",
    directors: "Makoto Shinkai",
    writers: "Makoto Shinkai",
    actor: "Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Narita",
    genres: "Animation, Drama, Fantasy, Romance",
    duration: "106 min",
    language: "Japanese",
    releaseDate: "7 April 2017",
    disambiguation: "PG",
    rating: 8.4,
    trailer: "https://www.youtube.com/embed/_mifHzxFNQ4",
  },
  {
    id: 7,
    image: "/images/walle.png",
    title: "WALL·E",
    year: "2008",
    nation: "USA",
    description:
      "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
    directors: "Andrew Stanton",
    writers: "Andrew Stanton, Pete Docter, Jim Reardon",
    actor: "Ben Burtt, Elissa Knight, Jeff Garlin",
    genres: "Animation, Adventure, Family, Sci-Fi",
    duration: "98 min",
    language: "English",
    releaseDate: "27 June 2008",
    disambiguation: "G",
    rating: 8.4,
    trailer: "https://www.youtube.com/embed/CZ1CATNbXg0",
  },
  {
    id: 8,
    image: "/images/elemental.png",
    title: "Elemental",
    year: "2023",
    nation: "Unknown",
    description:
      "Follows Ember and Wade, in a city where fire-, water-, earth- and air-residents live together.",
    directors: "Christopher Nolan",
    writers: "Christopher Nolan",
    actor: "Leah Lewis, Mamoudou Athie, Ronnie Del Carmen",
    genres: "Animation, Adventure, Family, Fantasy",
    duration: "142 min",
    language: "English",
    releaseDate: "7 July 2023",
    disambiguation: "PG-13",
    rating: 7.8,
    trailer: "https://www.youtube.com/embed/hXzcyx9V0xw",
  },
  {
    id: 9,
    image: "/images/interstellar.png",
    title: "Interstellar",
    year: "2014",
    nation: "USA",
    description:
      "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    directors: "Christopher Nolan",
    writers: "Jonathan Nolan, Christopher Nolan",
    actor: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    genres: "Adventure, Drama, Sci-Fi, Thriller",
    duration: "169 min",
    language: "English",
    releaseDate: "7 November 2014",
    disambiguation: "PG-13",
    rating: 8.6,
    trailer: "https://www.youtube.com/embed/zSWdZVtXT7E",
  },
  {
    id: 10,
    image: "/images/greenbook.png",
    title: "Green Book",
    year: "2018",
    nation: "USA",
    description:
      "A working-class Italian-American bouncer becomes the driver of an African-American classical pianist on a tour of venues through the 1960s American South.",
    directors: "Peter Farrelly",
    writers: "Nick Vallelonga, Brian Hayes Currie, Peter Farrelly",
    actor: "Viggo Mortensen, Mahershala Ali, Linda Cardellini",
    genres: "Biography, Comedy, Drama, Music",
    duration: "130 min",
    language: "English, Italian, Russian, German",
    releaseDate: "16 November 2018",
    disambiguation: "PG-13",
    rating: 8.2,
    trailer: "https://www.youtube.com/embed/QkZxoko_HC0",
  },
];
